const WORD_DATA = `
MIDNIGHT INK PRINT STAMP MIST MOTH DUSK EMBER
RAIL WAVE LOCK BEAM GLOW TONE GRID THE AND FOR THAT YOU WITH THIS WAS ARE HAVE NOT BUT FROM YOUR ALL HIS THEY ONE CAN
WILL JUST LIKE ABOUT OUT WHAT HAS WHEN MORE WERE WHO HAD THEIR THERE HER WHICH TIME GET BEEN WOULD SHE NEW PEOPLE HOW
SOME ALSO THEM NOW OTHER ITS OUR THAN GOOD ONLY AFTER FIRST HIM INTO KNOW SEE TWO MAKE OVER THINK ANY THEN COULD BACK
THESE WANT BECAUSE WELL SAID WAY MOST MUCH VERY WHERE EVEN SHOULD MAY HERE NEED REALLY DID RIGHT WORK YEAR YEARS BEING
DAY TOO GOING BEFORE OFF WHY MADE STILL TAKE GOT MANY NEVER THOSE LIFE SAY WORLD DOWN GREAT THROUGH LAST WHILE BEST
SUCH LOVE MAN HOME LONG LOOK USE SAME USED BOTH EVERY COME PART STATE THREE AROUND BETWEEN ALWAYS BETTER FIND HELP
HIGH LITTLE OLD SINCE ANOTHER DOES OWN THINGS UNDER DURING GAME THING GIVE HOUSE PLACE SCHOOL AGAIN NEXT EACH WITHOUT
AGAINST END FOUND MUST SHOW BIG FEEL SURE TEAM EVER FAMILY KEEP MIGHT PLEASE PUT MONEY FREE SECOND SOMEONE AWAY LEFT
NUMBER CITY DAYS LOT NAME NIGHT PLAY UNTIL COMPANY DOING FEW LET REAL CALLED HAVING SET THOUGHT DONE HOWEVER GETTING
GROUP LOOKING PUBLIC TOP WOMEN BUSINESS CARE START SYSTEM TIMES WEEK ALREADY ANYTHING CASE NOTHING PERSON TODAY CHANGE
ENOUGH FULL LIVE MAKING POINT READ TOLD YET BAD FOUR HARD MEAN ONCE SUPPORT TELL MUSIC POWER SEEN STOP WATER BASED
BELIEVE CALL HEAD MEN NATIONAL SMALL TOOK WHITE CAME FAR JOB SIDE THOUGH TRY WENT YES ACTUALLY LATER LESS LINE ORDER
PARTY RUN SAYS SERVICE COUNTRY OPEN SEASON THANK CHILDREN EVERYONE GENERAL TRYING USING AREA BLACK LAW MAKES TOGETHER
WAR WHOLE CAR FACE FIVE KIND MAYBE PER STORY WORKING COURSE GAMES HEALTH HOPE LEAST MEANS NEWS WITHIN ABLE BOOK EARLY
FRIENDS LOCAL POST THANKS VIDEO YOUNG AGO OTHERS SOCIAL TALK COURT FACT GIVEN GUYS HALF HAND LEVEL MIND OFTEN SINGLE
BECOME BODY COMING CONTROL DEATH FOOD GUY HOURS OFFICE PAY PROBLEM SOUTH TRUE ALMOST HISTORY KNOWN LARGE LOST RESEARCH
ROOM SEVERAL STARTED TAKING WIN WRONG ALONG ANYONE ELSE GIRL MATTER PRETTY REMEMBER AIR BIT FRIEND HIT NEEDS NICE
PLAYING PROBABLY SAYING CLASS CLOSE COMES IDEA LOOKS PAST POSSIBLE WANTED CAUSE DUE HAPPY HUMAN MEMBERS MONTHS MOVE
QUESTION SERIES WAIT WOMAN ASK DATA LATE LEAVE NORTH SAW SPECIAL WATCH EITHER FUTURE LIGHT LOW MILLION MORNING POLICE
SHORT STAY TAKEN AGE BUY DEAL RATHER REASON RED REPORT SOON THIRD TURN WHETHER AMONG CHECK FORM FURTHER HEART MINUTES
MYSELF SERVICES YOURSELF ACT ALTHOUGH ASKED CHILD FIRE FUN LIVING MAJOR MEDIA PHONE PLAYERS ART BEHIND BUILDING EASY
GONNA MARKET NEAR NON PLAN QUITE SIX TALKING WEST WORKS FINAL FORMER FRONT KIDS LIST READY SON STREET BRING COLLEGE
CURRENT EXAMPLE HEARD MEET PROGRAM TYPE BABY CHANCE FATHER PROCESS SONG STUDY WORD ACROSS ACTION CLEAR GAVE GETS
HIMSELF MONTH OUTSIDE SELF STUDENTS WORDS BOARD COST CUT FIELD HELD INSTEAD MAIN MOMENT MOTHER ROAD SEEMS THINKING
TOWN WANTS ENERGY FIGHT FINE FORCE HEAR ISSUE PLAYED POINTS PRICE REST RESULTS RUNNING SHOWS SPACE SUMMER TERM WIFE
DATE GOES LAND MISS PROJECT SHOT SITE STRONG ACCOUNT EYES INCLUDE PARENTS PERIOD POSITION RECORD SIMILAR TOTAL ABOVE
CLUB COMMON DIED FILM HAPPENED KNEW LEAD LIKELY MILITARY PERFECT PERSONAL SECURITY SHARE WON CENTER COUNTY COUPLE DEAD
HAPPEN HOLD INDUSTRY INSIDE ISSUES PLAYER PRIVATE PROBLEMS RETURN RIGHTS SENSE STAR TEST VIEW WEEKS BREAK EVENT HIGHER
HOUR MEMBER MIDDLE NEEDED PRESENT RESULT SORRY TAKES TRAINING WISH ANSWER BOY DESIGN FINALLY GIRLS GOLD GONE GUESS
INTEREST LEARN POLICY SOCIETY ADDED ALONE AVERAGE BANK BROUGHT CERTAIN CHURCH EAST HANDS HOT LONGER MEDICAL MOVIE
ORIGINAL PARK PRESS RECEIVED ROLE SENT TRIED WORKED WORTH AREAS BECAME BOOKS COOL DIRECTOR EXACTLY GIVING GROUND
MEETING PROVIDE SOUND SOURCE USUALLY VALUE EVIDENCE FOLLOW LIVES OFFICIAL RATE READING ROUND SAVE STAND STUFF TAX
WHATEVER AMOUNT BLUE DRIVE EAT FALL FAST FEDERAL FEELING FELT GREEN LEAGUE MATCH MODEL PICTURE SIZE STEP TRUST CENTRAL
CHANGES FORWARD GROUPS HEY KEY MOM PAGE PAID RANGE REVIEW SCIENCE TRADE UPON VARIOUS BROTHER CANNOT CHIEF CUP FOOTBALL
LED LOOKED LOWER NATURAL PROPERTY QUALITY SEND STYLE VOTE AMAZING COMPLETE DOG ECONOMIC INVOLVED ITSELF LANGUAGE OIL
RELATED SERIOUS STAGE TERMS TITLE ADD ARTICLE ATTACK BORN DECIDED DECISION ENJOY ENTIRE MET PERHAPS POOR RELEASE
TURNED WEBSITE WRITTEN CHOICE CODE CONTINUE COUNCIL COVER DOOR ELECTION EVENTS FOREIGN HAIR INCREASE LEGAL LOSE PICK
RACE SEEM SEVEN SIGN SIMPLE SIMPLY STAFF SUPER UNION WALK BED BEGAN BUILT CAREER CHANGED CRAZY DAILY DAUGHTER DIE
FIGURE HOSPITAL KNOWS LOSS MODERN ONES PAPER PARTS POPULAR SAFE STARTING SYSTEMS VERSION VOICE WHOSE WRITING ARMY
EARTH FORGET GOAL HUGE INTERNET LISTEN PRACTICE RULES SEA SIR SUCCESS TOWARDS WAITING WAYS ACCESS BASE BELOW CREATED
DEEP FOLLOWED MISSING OFFER PASS RELEASED RISK SCHOOLS SLEEP TABLE TEN TRUTH BALL BOX BUILD CARD CASES DARK DISTRICT
MINE MINISTER NOTE PERCENT PIECE PRODUCTS RECENT SEEING STRAIGHT VISIT WALL WANNA WROTE ALLOWED BOYS CULTURE ETC FANS
GIVES GROWTH INCLUDED MARRIED OFFICER PAIN PLACES RESPECT RESPONSE RIVER ROCK SHALL SPEAK SPECIFIC STANDARD TONIGHT
WRITE ALBUM CENTURY CHARGE COLD CREATE EFFECT EIGHT EXCEPT EYE FUNNY LIMITED MOVING NETWORK PEACE PROVIDED RECENTLY
REQUIRED SALES SPENT STORE STUDENT TOMORROW TRACK VIA WATCHING WEIGHT ADDITION AHEAD ALLOW ANTI BEAT BROWN CAPITAL
DOUBLE EXPECT GAS ISLAND MOVED NORMAL PLANS PRESSURE RADIO STATION TEXT WESTERN CAMPAIGN CONTENT CREDIT CROSS DESPITE
FEMALE FOCUS HUSBAND ICE JOIN KEPT LEADING LOVED MESSAGE MILES NEARLY PREVIOUS QUICKLY REGION REPORTED SECTION SORT
SPEED TRAVEL CONSIDER CONTACT DROP FAIR FEET KID LINK POSITIVE SALE TOUR WELCOME BEYOND EARLIER EXTRA FORCES JOBS
LEAVING MINUTE NATURE NUMBERS QUICK SELL STUDIES UNLESS WINNING AGREE CLEAN COMPUTER EPISODE FAVORITE INCOME JUSTICE
LEVELS MANAGER MOVEMENT PHOTO POSTED SAFETY SAN SCENE SOLD SOUNDS SPEND SUN TEAMS ABILITY ASKING CALLING COACH COSTS
DESIGNED EXPECTED HAPPENS HEAVY INCLUDES SEARCH SUBJECT TRAIN WIDE WOW AUTHOR CENTRE CLAIM DAD FEAR FIT GLOBAL GOALS
GOTTA HOTEL JUDGE LADY LEADER LETTER LINES MATERIAL NAMED NOBODY PLUS PRE PRODUCT REGULAR SISTER STORIES UNIT WORKERS
ANNUAL ANYMORE BAR BATTLE BRAIN CONTRACT DEGREE FAMILIES FEATURES FINISHED FLOOR GROWING HURT IMAGE MAJORITY MEANT
OPENING OPINION PHYSICAL PRO REACH RULE SPORTS STUPID ACTIVE APPROACH BIGGEST CANCER CIVIL DANCE DEFENSE MASTER NONE
REASONS SHIP STOCK TRUMP WEEKEND WONDER WORST AWESOME BAND BEACH CASH CLEARLY COMPARED EFFORT ENDED FAN FIGHTING
IMAGINE IMPACT LACK LATEST LEARNING MULTIPLE OLDER PASSED PICTURES PROTECT SECRET SENIOR SPRING TELLING WEAR ADDRESS
ANALYSIS ANYWAY BOUGHT CALLS CHOOSE COLOR DETAILS DIRECT DREAM EASILY FINISH GRAND LUCK MARRIAGE NAMES PATIENTS RICH
SKIN SPEAKING SUPPOSED SWEET THUS TOUCH CAUGHT CLOSED CONGRESS DAMAGE DIRECTLY DISEASE DOCTOR DOUBT DRINK DRIVING
FEELS FISH GAY GLAD GREATER GROW LARGEST MACHINE NOTICE OVERALL PLANNING PROGRAMS RECORDS REPORTS SHOWN SIT TRIP BASIC
CAPTAIN CARRY CARS CRIME EFFECTS EXPLAIN FULLY HIGHLY HOLDING LAWS MALE MRS PARTIES PLANT REALITY SPOT WINTER WORSE
ADVICE AWARD BLOCK BROKEN CAUSED COMMENT HELPED HOLY LIVED LOTS NATION PRICES PRIMARY PURPOSE RATES SHOP SHOWING SICK
TEACHER THEORY USES AGENCY AVOID CAMERA CATCH CELL COAST COMMENTS ECONOMY FOOT HALL MASS MEANING MISSION NINE OFFICERS
POLITICS POP PRODUCED RAN STATUS TRIAL TRULY WEATHER ACTIVITY APP CLAIMS COFFEE COMPLEX DIVISION EVENING FLIGHT
FREEDOM HEAT HIGHEST LIBRARY LOCATED LOCATION OBAMA OFFERED PUTTING QUEEN SECONDS SHOWED SITTING STANDING STARS
WALKING ACCEPT ACTUAL APPEAR ATTEMPT BROKE CHANNEL DISTANCE EATING EXCHANGE FAT FELL FINDING GLASS LEARNED LOSING
MOBILE NORTHERN OPENED PLACED POWERFUL PRIOR REACHED RECEIVE RIDE ROYAL SCREEN SERVE SIGNED SLOW SPECIES SPEECH
TRAFFIC TREE TYPES WEARING WHOM AGREED AIRPORT ANIMALS APPEARS BEGIN BENEFITS BOTTOM CITIES DEMAND ENGINE FAMOUS IDEAS
KEEPING LIE NOTES PARTNER PLAYS RAISED RUNS SAD SOLUTION SONGS SOURCES SOUTHERN SQUARE STOPPED TWICE WIND WORRY
APPEARED BECOMES BRAND BUS CENT CHICAGO COUNT COVERED CRITICAL DIGITAL FORCED FOURTH FRESH LAKE MENTAL MISSED MOSTLY
MOUTH OWNER PHOTOS REALIZE REMAIN SCALE SCORE SEPARATE SMART STARTS SURFACE THROW TOTALLY VIEWS WEDDING ACTING ACTIONS
ARMS BENEFIT BUDGET ESTATE FAILED FAITH FASHION FEATURE FUND HEARING HILL LARGER METAL MID PROFILE PULL PUSH RETURNED
ROSE SEAT SEEMED SEXUAL TARGET VILLAGE AGENT ANIMAL APPLY BASIS BECOMING DRAW DUDE ENTER FOLLOWS GAIN LEADERS MEMORY
PRIME PROJECTS RING RISE SELLING SERVED SILVER SOUL SPREAD SUPPLY WASTE WEIRD ADULT ARTIST CHAIRMAN EDITION GRADE
HEALTHY METHOD NATIONS OPTION PRISON PROVIDES REMAINS SENATE SMALLER SOMEBODY STONE STRENGTH USERS WILD WINDOW WINNER
ARRIVED BAG BET CAMP CAST CORRECT FIRM GREATEST HANDLE IMPROVE INDEED LEAVES MOVIES NEGATIVE PREVENT REMOVED SPIRIT
TILL TROUBLE VIDEOS APART AWARE CAT DECIDE DINNER DOLLARS EASTERN FIFTH FUNCTION GIFT HELPING HERSELF ITEMS JOE LOS
NOR PRODUCE PROGRESS PROUD REQUIRE SHOOTING SHUT TELLS THINKS VAN WOOD BIRTH BRIDGE CARRIED CLASSES CONCEPT COPY DEAR
DOGS EFFORTS GARDEN HOST HOUSING INC ISRAEL JOURNAL LABOR LENGTH LUCKY NEITHER ONTO PATIENT POSSIBLY PROVE RARE
SETTING SKILLS SOFTWARE TOUGH UNITS ALIVE BALANCE BIRTHDAY BOSS CARDS CHANGING DRESS EASIER FELLOW HORSE KNOWING LIKED
MAGIC MANAGED MAP NET OWNED REQUEST STICK TURNS VEHICLE VOLUME WAKE AID BEAUTY BELIEVED BILLION BUSY BUYING CELLS
CORNER CRIMINAL CULTURAL DEVELOP DRIVER ENDS EXISTING FARM FILE FIX FLY GUIDE IMAGES PAYING RAISE ROLL SLIGHTLY
SUGGEST SURPRISE THOUGHTS TREAT UNIQUE VARIETY VIOLENCE WEAPONS YOURS YOUTH BIGGER BREAKING DONT DRY EDGE EVIL EXCITED
FOREVER FUNDS HELPS INJURY IRON LOVELY MAD MAGAZINE MODELS OFFERS ORDERED PREPARED RELIGION SITES STATED STRATEGY
TEACHERS WEB WINE ACCOUNTS ANGELES ARM AUDIENCE BAY BLOG CLOSER CORE DROPPED EXIST FIGURES FORMS GUARD HONEST ISSUED
JOINED JONES LEE LIES LIKES MEDICINE MENTION MOUNTAIN NUCLEAR ORDERS PORT PRESENCE REACTION REDUCE SHOOT SIDES SOLID
SPORT STEPS STRESS TASTE TEA VICTORY CITIZENS CLASSIC CLOTHES ELECTRIC ENTERED ENTIRELY FACTS FAILURE FESTIVAL FLAT
FUEL HELLO HOUSES ILL INITIAL JOHNSON KICK LINKS MAIL MASSIVE MATTERS PAIR PICKED PIECES PLANE PLENTY PRINCE PROPER
QUARTER REGIONAL SESSION SHAPE SKY TEACHING TOWARD TRANSFER UPPER USEFUL VALLEY WATCHED WILLING ZONE ACCIDENT ADVANCED
ANYWHERE ARTICLES AWARDS BEAR BOAT BRINGING CAPACITY CHEAP CLIMATE DRINKING DUTY FEELINGS FLYING GOVERNOR HUNDRED
JOINT MIX MUSEUM OPTIONS PATH PLANTS POLICIES PROMISE PROPOSED PURCHASE RAIN REMOVE SIGNS SPENDING STEEL TERRIBLE
TIRED TREATED TURNING VICE WARM AFRAID ARTS BEER BORDER CANADIAN COMMAND CREW CROWD DATING ELEMENTS ENEMY ENSURE
FILLED FIXED FOREST INTENDED LABOUR LIMIT MOON OCEAN POWERS PROFIT PROOF SOLDIERS SUIT WINS ATTORNEY BANKS BEHAVIOR
BODIES BROTHERS CHAIR CREATING DEBT DOMESTIC GREW HOMES HONESTLY HONOR JUMP LAUNCH LISTED MINIMUM NATIVE NOTED PLANNED
RAY SETS SUDDENLY SUPREME SURVEY TECH TREES UPDATE USER WRITER YELLOW YOUNGER ANCIENT ATTACKS CHARGES COMBINED
CONTAINS DOWNLOAD ENDING EXERCISE EXPRESS FLOW FORMED HERO ILLEGAL JOKE LOAN METHODS PLANET SELECTED SHARED SHOPPING
SOFT STUCK SUGAR TAUGHT ACCEPTED ADDING AFFAIRS ALLOWS APPEAL APPLIED ARTISTS DEVICE DRAMA ENTRY ERA FACTOR FEED
GOLDEN GRANT GROWN HEADS HOPING KEEPS LAWYER LEGS LYING MEASURES MISTAKE PLATFORM POOL PULLED REQUIRES ROUTE SAVED
SCHEDULE SHOES SMOKE SQUAD TEACH TESTING TESTS VALUES WALKED ANGRY CONCERN DISCUSS FALLING HOLE HOLIDAY INTERNAL LAUGH
LEG LETTERS LIBERAL LOVES LUNCH MAX MILK PACK PAYMENT PERFORM RECORDED SECTOR SHARING SNOW STORM STREETS STRIKE STUDIO
SUB WEAK ACTOR ADVANCE CHAIN CHAPTER COOK CUTE EQUAL FAKE FINANCE FOCUSED HITS IDENTITY JOURNEY KITCHEN LEADS MAINTAIN
MEASURE NUMEROUS
`;

const WORDS = WORD_DATA.trim().split(/\s+/);
const WORD_SET = new Set(WORDS);

export const WORDS_BY_LENGTH = new Map<number, string[]>();

for (const word of WORDS) {
  const bucket = WORDS_BY_LENGTH.get(word.length) ?? [];
  bucket.push(word);
  WORDS_BY_LENGTH.set(word.length, bucket);
}

export function isWord(candidate: string): boolean {
  return WORD_SET.has(candidate.toUpperCase());
}
