#!/usr/bin/env node
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';

const root = process.cwd();
const registryPath = path.join(root, 'src', 'levels', 'index.ts');
const registry = await readFile(registryPath, 'utf8');
const order = parseRegistryOrder(registry);
const imports = parseSwitchImports(registry);

const sections = [];
for (const { id } of order) {
  const modulePath = imports.get(id) ?? `./${id}`;
  const dir = modulePath.replace(/^\.\//, '');
  const cardPath = path.join(root, 'src', 'levels', dir, 'level.md');
  try {
    sections.push((await readFile(cardPath, 'utf8')).trimEnd());
  } catch (error) {
    if (error?.code === 'ENOENT') throw new Error(`Missing identity card for ${id}: src/levels/${dir}/level.md`);
    throw error;
  }
}

const header = `# Level gallery\n\nGenerated by \`npm run gallery\`. Edit \`src/levels/<id>/level.md\`, then re-run \`npm run gallery\`.\n`;
await writeFile(path.join(root, 'docs', 'level-gallery.md'), `${header}\n${sections.join('\n\n---\n\n')}\n`);
console.log(`Wrote docs/level-gallery.md from ${sections.length} level cards`);

function parseRegistryOrder(source) {
  const arrayMatch = source.match(/export const levelMetadatas: LevelMetadata\[] = \[([\s\S]*?)\n\];/);
  if (!arrayMatch) throw new Error('Could not find levelMetadatas array');
  const entries = [];
  const entryRegex = /\{\s*id:\s*'([^']+)'\s*,\s*title:\s*'([^']+)'/g;
  let match;
  while ((match = entryRegex.exec(arrayMatch[1]))) entries.push({ id: match[1], title: match[2] });
  return entries;
}

function parseSwitchImports(source) {
  const map = new Map();
  const caseRegex = /case '([^']+)':\s*\n\s*return \(await import\('([^']+)'\)\)\.[A-Za-z0-9_]+;/g;
  let match;
  while ((match = caseRegex.exec(source))) map.set(match[1], match[2]);
  return map;
}
