import { readFile, readdir } from 'node:fs/promises';
import path from 'node:path';

// Single source of truth for docs/level-gallery.md, shared by `npm run gallery`
// (scripts/collect-gallery.mjs) and the floor gate (scripts/check-floor-cli.ts)
// so they agree byte-for-byte. Built-in cards come first in registry order;
// auto-discovered benchmark levels follow so an entrant that regenerates the
// gallery includes its own card and passes the floor gate. With no benchmark
// levels present the output is identical to the built-in-only gallery.
export async function buildGallery(root) {
  const sections = [...(await readBuiltInCards(root)), ...(await readBenchmarkCards(root))];
  const header = `# Level gallery\n\nGenerated by \`npm run gallery\`. Edit \`src/levels/<id>/level.md\`, then re-run \`npm run gallery\`.\n`;
  return `${header}\n${sections.join('\n\n---\n\n')}\n`;
}

async function readBuiltInCards(root) {
  const registryPath = path.join(root, 'src', 'levels', 'index.ts');
  const registry = await readFile(registryPath, 'utf8');
  const order = parseRegistryOrder(registry);
  const imports = parseSwitchImports(registry);
  const cards = [];
  for (const { id } of order) {
    const modulePath = imports.get(id) ?? `./${id}`;
    const dir = modulePath.replace(/^\.\//, '');
    cards.push(await readCard(path.join(root, 'src', 'levels', dir, 'level.md'), `src/levels/${dir}/level.md`));
  }
  return cards;
}

async function readBenchmarkCards(root) {
  const benchmarkRoot = path.join(root, 'src', 'benchmark-levels');
  let entries;
  try {
    entries = await readdir(benchmarkRoot, { withFileTypes: true });
  } catch (error) {
    if (error?.code === 'ENOENT') return [];
    throw error;
  }
  const cards = [];
  const dirs = entries
    .filter((entry) => entry.isDirectory() && entry.name !== 'test-fixtures')
    .sort((a, b) => a.name.localeCompare(b.name));
  for (const dir of dirs) {
    // Only auto-discovered levels (those carrying a descriptor) contribute cards.
    try {
      await readFile(path.join(benchmarkRoot, dir.name, 'level.json'), 'utf8');
    } catch (error) {
      if (error?.code === 'ENOENT') continue;
      throw error;
    }
    cards.push(await readCard(path.join(benchmarkRoot, dir.name, 'level.md'), `src/benchmark-levels/${dir.name}/level.md`));
  }
  return cards;
}

async function readCard(cardPath, displayPath) {
  try {
    return (await readFile(cardPath, 'utf8')).trimEnd();
  } catch (error) {
    if (error?.code === 'ENOENT') throw new Error(`Missing identity card for ${displayPath}`);
    throw error;
  }
}

function parseRegistryOrder(source) {
  const arrayMatch = source.match(/export const levelMetadatas: LevelMetadata\[] = \[([\s\S]*?)\n\];/);
  if (!arrayMatch) throw new Error('Could not find levelMetadatas array');
  const entries = [];
  const entryRegex = /\{\s*id:\s*'([^']+)'\s*,\s*title:\s*'([^']+)'/g;
  let match;
  while ((match = entryRegex.exec(arrayMatch[1]))) entries.push({ id: match[1], title: match[2] });
  return entries;
}

function parseSwitchImports(source) {
  const map = new Map();
  const caseRegex = /case '([^']+)':\s*\n\s*return \(await import\('([^']+)'\)\)\.[A-Za-z0-9_]+;/g;
  let match;
  while ((match = caseRegex.exec(source))) map.set(match[1], match[2]);
  return map;
}
