import { readFile } from 'node:fs/promises';
import path from 'node:path';

export async function buildGallery(root) {
  const builtIns = await readBuiltInCards(root);
  const header = '# Level gallery\n\nGenerated by `npm run gallery`. Edit `src/levels/<id>/level.md`, then re-run `npm run gallery`.\n';
  return `${header}\n## Built-in levels\n\n${builtIns.join('\n\n---\n\n')}\n`;
}

async function readBuiltInCards(root) {
  const registryPath = path.join(root, 'src', 'levels', 'index.ts');
  const registry = await readFile(registryPath, 'utf8');
  const order = parseRegistryOrder(registry);
  const imports = parseSwitchImports(registry);
  const cards = [];
  for (const { id } of order) {
    const modulePath = imports.get(id) ?? `./${id}`;
    const dir = modulePath.replace(/^\.\//, '');
    cards.push(await readCard(path.join(root, 'src', 'levels', dir, 'level.md'), `src/levels/${dir}/level.md`));
  }
  return cards;
}

async function readCard(cardPath, displayPath) {
  try {
    return (await readFile(cardPath, 'utf8')).trimEnd();
  } catch (error) {
    if (error?.code === 'ENOENT') throw new Error(`Missing identity card for ${displayPath}`);
    throw error;
  }
}

function parseRegistryOrder(source) {
  const arrayMatch = source.match(/export const levelMetadatas: (?:LevelMetadata|BuiltInLevelMetadata)\[\] = \[([\s\S]*?)\n\];/);
  if (!arrayMatch) throw new Error('Could not find levelMetadatas array');
  const entries = [];
  const entryRegex = /\{\s*id:\s*'([^']+)'\s*,\s*title:\s*'([^']+)'/g;
  let match;
  while ((match = entryRegex.exec(arrayMatch[1]))) entries.push({ id: match[1], title: match[2] });
  return entries;
}

function parseSwitchImports(source) {
  const map = new Map();
  // Built-in loaders are part of the human-maintained registry, and the gallery
  // covers built-in levels only.
  const loaderRegex = /'([^']+)': async \(\) => \(await import\('([^']+)'\)\)/g;
  let match;
  while ((match = loaderRegex.exec(source))) map.set(match[1], match[2]);
  return map;
}
