import { readFile } from 'node:fs/promises';
import path from 'node:path';

export async function buildGallery(root) {
  const cards = await collectBuiltInCards(root);
  const header = '# Level gallery\n\nGenerated by `npm run gallery`. Edit `src/levels/<id>/level.md`, then re-run `npm run gallery`.\n';
  return `${header}\n## Built-in levels\n\n${cards.map((card) => card.raw).join('\n\n---\n\n')}\n`;
}

/** Structured, player-facing notes for each built-in level, consumed by the
 * website's levels page. Two parts of the identity card stand on their own for a
 * player: the intro paragraph beneath the title, and the "What to study here"
 * section (rendered as candid builder's-eye notes). The remaining sections —
 * What to read, Status & notes — are agent-only and left out. */
export async function buildBuiltInNotes(root) {
  const cards = await collectBuiltInCards(root);
  return cards.map((card) => ({ id: card.id, ...parseCard(card.raw) }));
}

/** Emit the notes as a committed TS module. Same discipline as the rank
 * catalog: generated, never hand-edited, imported by the app. */
export function renderBuiltInNotesModule(records) {
  const banner = '// Generated by `npm run gallery` from src/levels/<id>/level.md.\n'
    + '// Do not edit by hand — edit the level.md sources and re-run the script.\n\n';
  const type = 'export interface BuiltInLevelNotes {\n'
    + '  /** Player-facing intro paragraph, from the text beneath the card title. */\n'
    + '  readonly intro: string;\n'
    + '  /** Candid builder\'s-eye notes, from the card\'s "What to study here" section. */\n'
    + '  readonly builderNotes: readonly string[];\n'
    + '}\n\n';
  const entries = records.map((record) =>
    `  ${JSON.stringify(record.id)}: {\n`
    + `    intro: ${JSON.stringify(record.intro)},\n`
    + `    builderNotes: ${JSON.stringify(record.builderNotes)},\n`
    + '  },').join('\n');
  return `${banner}${type}export const builtInLevelNotes: Record<string, BuiltInLevelNotes> = {\n${entries}\n};\n`;
}

async function collectBuiltInCards(root) {
  const registryPath = path.join(root, 'src', 'levels', 'index.ts');
  const registry = await readFile(registryPath, 'utf8');
  const order = parseRegistryOrder(registry);
  const imports = parseSwitchImports(registry);
  const cards = [];
  for (const { id } of order) {
    const modulePath = imports.get(id) ?? `./${id}`;
    const dir = modulePath.replace(/^\.\//, '');
    const displayPath = `src/levels/${dir}/level.md`;
    const raw = await readCard(path.join(root, 'src', 'levels', dir, 'level.md'), displayPath);
    cards.push({ id, dir, displayPath, raw });
  }
  return cards;
}

async function readCard(cardPath, displayPath) {
  try {
    return (await readFile(cardPath, 'utf8')).trimEnd();
  } catch (error) {
    if (error?.code === 'ENOENT') throw new Error(`Missing identity card for ${displayPath}`);
    throw error;
  }
}

/** Split a level identity card into its player-facing parts: the intro
 * paragraph beneath the `# Title`, and the paragraphs of the "What to study
 * here" section. The text is taken verbatim — inline code spans and all — and
 * only reflowed to single-line paragraphs for the data module. */
function parseCard(raw) {
  const heading = raw.match(/^#\s+(.+?)\s*$/m);
  const afterTitle = heading ? raw.slice(heading.index + heading[0].length) : raw;
  const introEnd = afterTitle.search(/^##\s+/m);
  const intro = paragraphs(introEnd === -1 ? afterTitle : afterTitle.slice(0, introEnd)).join(' ');
  return { intro, builderNotes: sectionParagraphs(raw, 'What to study here') };
}

function sectionParagraphs(raw, name) {
  const heading = new RegExp(`^##\\s+${escapeRegExp(name)}\\s*$`, 'm');
  const match = raw.match(heading);
  if (!match) return [];
  const rest = raw.slice(match.index + match[0].length);
  const next = rest.search(/^##\s+/m);
  return paragraphs(next === -1 ? rest : rest.slice(0, next));
}

/** Blank-line-separated paragraphs, each reflowed to a single line. */
function paragraphs(block) {
  return block
    .trim()
    .split(/\n\s*\n/)
    .map((paragraph) => paragraph.replace(/\s*\n\s*/g, ' ').trim())
    .filter(Boolean);
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function parseRegistryOrder(source) {
  const arrayMatch = source.match(/export const levelMetadatas: (?:LevelMetadata|BuiltInLevelMetadata)\[\] = \[([\s\S]*?)\n\];/);
  if (!arrayMatch) throw new Error('Could not find levelMetadatas array');
  const entries = [];
  const entryRegex = /\{\s*id:\s*'([^']+)'\s*,\s*title:\s*'([^']+)'/g;
  let match;
  while ((match = entryRegex.exec(arrayMatch[1]))) entries.push({ id: match[1], title: match[2] });
  return entries;
}

function parseSwitchImports(source) {
  const map = new Map();
  // Built-in loaders are part of the human-maintained registry, and the gallery
  // covers built-in levels only.
  const loaderRegex = /'([^']+)': async \(\) => \(await import\('([^']+)'\)\)/g;
  let match;
  while ((match = loaderRegex.exec(source))) map.set(match[1], match[2]);
  return map;
}
